modules_tsxmlinvoice_generate:
  path: /tsxmlinvoice/generate/{id_order}
  methods: [GET]
  defaults:
    _controller: 'Modules\\Tsxmlinvoice\\Controller\\Admin\\XmlInvoiceController::generateAction'
    _legacy_controller: 'AdminOrders'
    _legacy_link: 'AdminOrders'
  requirements:
    id_order: '\\d+'
