modules_tsxmlinvoice_generate:
  path: /modules/tsxmlinvoice/generate
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Tsxmlinvoice\Controller\Admin\XmlInvoiceController::generateAction'
    _legacy_controller: 'AdminOrders'
