tsxmlinvoice_generate:
  path: /modules/tsxmlinvoice/generate/{invoiceId}
  methods: [GET]
  defaults:
    _controller: 'tsxmlinvoice.controllers.admin.tsxmlinvoice:generateAction'
    invoiceId: null
