services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Modules\Tsxmlinvoice\Controller\Admin\XmlInvoiceController:
    class: Modules\Tsxmlinvoice\Controller\Admin\XmlInvoiceController
