services:
  tsxmlinvoice.controllers.admin.tsxmlinvoice:
    class: PrestaShop\Module\Tsxmlinvoice\Controller\Admin\TsXmlInvoiceController
    public: true
    tags:
      - { name: controller.service_arguments }
