tsxmlinvoice_generate:
  path: /tsxmlinvoice/generate/{invoiceId}
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\\Module\\Tsxmlinvoice\\Controller\\Admin\\XmlInvoiceController::generate'
    _legacy_controller: 'AdminOrders'
    _legacy_link: 'AdminOrders'
  requirements:
    invoiceId: \d+
